CREATE TABLE Dishes(
	Name VARCHAR(24) PRIMARY KEY,
	TotalAmount VARCHAR(24) NOT NULL,
	Price SMALLMONEY NOT NULL
);

CREATE TABLE Ingredients(
	Name VARCHAR(24) PRIMARY KEY
);

CREATE TABLE Recipes(
	Id INT PRIMARY KEY IDENTITY,
	Dish_name VARCHAR(24) NOT NULL,
	Ingredient_name VARCHAR(24) NOT NULL,
	Amount VARCHAR(24) NOT NULL,

	FOREIGN KEY (Dish_name) REFERENCES Dishes(Name),
	FOREIGN KEY (Ingredient_name) REFERENCES Ingredients(Name)
);