CREATE TABLE Dishes(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(24) NOT NULL UNIQUE,
	TotalAmount VARCHAR(24) NOT NULL,
	Price SMALLMONEY NOT NULL
);

CREATE TABLE Ingredients(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(24) NOT NULL UNIQUE
);

CREATE TABLE Recipes(
	Id INT PRIMARY KEY IDENTITY,
	Dish_id INT NOT NULL,
	Ingredient_id INT NOT NULL,
	Amount VARCHAR(24) NOT NULL,

	FOREIGN KEY (Dish_id) REFERENCES Dishes(Id),
	FOREIGN KEY (Ingredient_id) REFERENCES Ingredients(Id)
);
